document.documentElement.classList.add('js');

const translations = {
  en: {
    navEducation: 'Education',
    navResearch: 'Research',
    navExperience: 'Experience',
    navSkills: 'Skills',
    navInterests: 'Interests',

    heroEyebrow: 'Fuzhou → Waterloo · Computer Science → Mathematical Economics',
    identityLine: '林灿然 (Canran Bruce Lin) is from Fuzhou, Fujian, China and studies at the University of Waterloo in Canada.',
    heroSummary: 'University of Waterloo student with a Computer Science background and current training in Mathematical Economics. Interested in interdisciplinary work combining programming, quantitative analysis, and applied research.',
    viewWork: 'View my work',
    downloadResume: 'Open résumé',
    portraitTitle: 'University of Waterloo',
    portraitSubtitle: 'BMath · Mathematical Economics',

    signalEducation: 'CS + Math Econ',
    signalEducationSub: 'Academic background',
    signalResearch: 'Applied research',
    signalResearchSub: 'Data, economics and AI',
    signalLocation: 'Fuzhou · Waterloo',
    signalLocationSub: 'China · Canada',

    educationKicker: 'Academic path',
    educationTitle: 'Education',
    educationIntro: 'A foundation in computer science followed by interdisciplinary training in mathematics and economics.',
    degreeLabel: 'Degree background',
    currentLabel: 'Current program',
    edu1Title: 'Bachelor of Computer Science (BCS)',
    edu2Title: 'Bachelor of Mathematics (BMath) in Mathematical Economics',
    uwLocation: 'University of Waterloo · Waterloo, Ontario, Canada',
    uwLocation2: 'University of Waterloo · Waterloo, Ontario, Canada',

    researchKicker: 'Questions into evidence',
    researchTitle: 'Research Experience',
    researchIntro: 'Research work spanning climate policy, language-model validation, public health and economic evaluation.',
    r1Role: 'Research Assistant',
    r1Org: 'Supervised by Prof. Yigang Wei · Jan 2026–Mar 2026',
    r1b1: 'Assisted with research on CCUS by contributing to manuscript revision and coding-related analysis for a paper currently under review.',
    r1b2: 'Built Python scripts to automate the validation of coding results generated by large language models, improving the efficiency of quality checking and inconsistency detection.',
    r1b3: 'Performed random sampling, manual verification, and calibration of generated outputs to improve coding reliability and overall accuracy.',
    r2Role: 'Research Assistant and Co-author',
    r2Org: 'Supervised by Prof. Xiangming Fang · Jan 2026–Mar 2026',
    r2b1: 'Contributed to a systematic review on the economic evaluation of interventions for preventing child sexual violence in educational settings within an economics-oriented research team.',
    r2b2: 'Collected and processed data on the prevalence of child sexual violence across multiple world regions and age groups.',
    r2b3: 'Applied programming and quantitative skills to streamline data cleaning in Python, improving the efficiency and consistency of data preparation for the study.',
    r2b4: 'Took primary responsibility for preparing sexual violence prevalence data used in the study and contributed as a co-author to a manuscript currently under review.',

    experienceKicker: 'From prototype to product',
    experienceTitle: 'Internship Experience',
    experienceIntro: 'Software development, AI translation, product iteration, front-end work and media production.',
    i1Org: 'Rockchip · 瑞芯微',
    i1Role: 'Software Developer Intern',
    i1b1: 'Contributed to the development of an AI-powered translation module for educational tablet products, supporting real-time subtitle translation for audio and video content.',
    i1b2: 'Integrated large language models including DeepSeek via API-based calls and implemented rule-based translation support to improve translation quality in child-oriented applications.',
    i1b3: 'Adjusted translation outputs to filter inappropriate language and better align generated content with educational use cases for children.',
    i1b4: 'Used Python and C++ to support development and testing, including scripts for collecting video samples from platforms such as YouTube, Bilibili, and Douyin for evaluation.',
    i2Role: 'Product Operations, Front-End, and Testing Intern',
    i2b1: 'Supported the launch and iteration of PicMa through front-end improvement, product testing, and product communication support.',
    i2b2: 'Contributed to front-end updates and testing workflows to improve product presentation and user experience.',
    i2b3: 'Produced promotional video materials and assisted with public-facing product content, including documentation related to PicMa.',
    i2b4: 'Used Python, JavaScript, Final Cut Pro, and CapCut across product support, testing, and media production tasks.',

    skillsKicker: 'Toolkit and foundations',
    skillsTitle: 'Academic Background & Skills',
    skillsIntro: 'A deliberately broad base across computation, mathematics, economics and scientific coursework.',
    csLabel: 'Computer Science',
    csText: 'Foundation in programming, data structures, object-oriented programming, logic and computation, and computer architecture.',
    mathLabel: 'Mathematics',
    mathText: 'Training in linear algebra, multivariable calculus, combinatorics, graph theory, optimization, probability, and statistics.',
    econLabel: 'Economics',
    econText: 'Coursework in microeconomics, macroeconomics, and world economy.',
    scienceLabel: 'Additional Science',
    scienceText: 'Also completed university coursework in chemistry and physics.',
    toolsLabel: 'Tools & Systems',
    toolsText: 'VS Code, Cursor, Vim, Git, LaTeX, Microsoft Office; editing with Final Cut Pro and CapCut. Comfortable with Linux, macOS, and Windows.',
    englishLevel: 'English · Fluent',
    chineseLevel: 'Mandarin Chinese · Native',

    interestsKicker: 'Beyond the desk',
    interestsTitle: 'Sports & Martial Arts',
    interestsIntro: 'Table tennis, Muay Thai, Sanda and Wing Chun are a continuing part of how I train, compete and think.',
    personalb1: 'Passed the selection process for the University of Waterloo table tennis team and joined the B team.',
    personalb2: 'Previously trained in Wing Chun and Sanda in China.',
    personalb3: 'Continued martial arts training at the University of Waterloo through Muay Thai practice.',
    galleryChina: 'Training in China',
    galleryWaterloo: 'Training in Waterloo',
    galleryTeam: 'University team selection',

    footerLocation: 'From Fuzhou · Based in Waterloo',
    footerRights: 'Personal academic portfolio.'
  },

  zh: {
    navEducation: '教育',
    navResearch: '科研',
    navExperience: '实习',
    navSkills: '能力',
    navInterests: '兴趣',

    heroEyebrow: '福州 → 滑铁卢 · 计算机科学 → 数理经济学',
    identityLine: '林灿然（Canran Bruce Lin）来自中国福建福州，现就读于加拿大滑铁卢大学（University of Waterloo）。',
    heroSummary: '具有计算机科学学习背景，现于滑铁卢大学接受数理经济学方向训练，关注编程、定量分析与应用研究相结合的跨学科工作。',
    viewWork: '查看经历',
    downloadResume: '打开简历',
    portraitTitle: '滑铁卢大学',
    portraitSubtitle: '数学学士 · 数理经济学',

    signalEducation: '计算机 + 数理经济',
    signalEducationSub: '跨学科学术背景',
    signalResearch: '应用研究',
    signalResearchSub: '数据、经济学与人工智能',
    signalLocation: '福州 · 滑铁卢',
    signalLocationSub: '中国 · 加拿大',

    educationKicker: '学术路径',
    educationTitle: '教育背景',
    educationIntro: '从计算机科学基础出发，进一步接受数学与经济学的跨学科训练。',
    degreeLabel: '学习背景',
    currentLabel: '当前专业',
    edu1Title: '计算机科学学士（BCS）',
    edu2Title: '数理经济方向数学学士（BMath）',
    uwLocation: '滑铁卢大学 · 加拿大安大略省滑铁卢',
    uwLocation2: '滑铁卢大学 · 加拿大安大略省滑铁卢',

    researchKicker: '从问题到证据',
    researchTitle: '科研经历',
    researchIntro: '研究方向涵盖气候政策、大语言模型结果校验、公共卫生与经济评估。',
    r1Role: '科研助理',
    r1Org: '导师：魏亿钢教授 · 2026年1月至3月',
    r1b1: '参与 CCUS 相关研究，协助论文修改与编码分析，相关论文目前处于审稿中。',
    r1b2: '使用 Python 脚本对大语言模型生成的编码结果进行自动化校验，提高质量检查与不一致识别的效率。',
    r1b3: '通过随机抽样、人工核验与校准，提升编码结果的可靠性与整体准确性。',
    r2Role: '科研助理兼联合作者',
    r2Org: '导师：方向明教授 · 2026年1月至3月',
    r2b1: '参与教育环境中儿童性暴力预防干预措施经济评估的系统综述研究，所在团队具有经济学导向。',
    r2b2: '收集并处理多个地区、不同年龄段儿童性暴力发生率相关数据。',
    r2b3: '将编程与定量分析能力应用于 Python 数据清洗流程中，提升研究数据准备的效率与一致性。',
    r2b4: '主要负责研究中所使用的性暴力发生率数据准备工作，并以联合作者身份参与一篇正在审稿中的论文。',

    experienceKicker: '从原型到产品',
    experienceTitle: '实习经历',
    experienceIntro: '涉及软件开发、人工智能翻译、产品迭代、前端工作与媒体制作。',
    i1Org: '瑞芯微 · Rockchip',
    i1Role: '软件开发实习生',
    i1b1: '参与教育平板产品 AI 翻译模块开发，支持音频与视频内容的实时字幕翻译。',
    i1b2: '接入 DeepSeek 等大语言模型的 API 调用，并结合规则式翻译辅助方案，提升儿童使用场景下的翻译质量。',
    i1b3: '根据教育场景需求，对输出内容进行不良词汇过滤与表达调整。',
    i1b4: '使用 Python 与 C++ 支持开发与测试，并编写脚本从 YouTube、哔哩哔哩、抖音等平台抓取视频样本用于评估。',
    i2Role: '产品运营、前端与测试实习生',
    i2b1: '参与 PicMa 产品上线与迭代，负责前端改进、产品测试及产品传播支持。',
    i2b2: '参与前端更新与测试流程优化，提升产品展示效果与用户体验。',
    i2b3: '制作产品宣传视频，并协助完成面向公众的产品内容与 PicMa 相关说明资料。',
    i2b4: '在产品支持、测试与媒体制作流程中使用 Python、JavaScript、Final Cut Pro 与剪映。',

    skillsKicker: '工具与学术基础',
    skillsTitle: '学术背景与技能',
    skillsIntro: '横跨计算机、数学、经济学与其他理科课程的复合基础。',
    csLabel: '计算机科学',
    csText: '具备编程、数据结构、面向对象程序设计、逻辑与计算理论、计算机体系结构等基础。',
    mathLabel: '数学',
    mathText: '接受过线性代数、多元微积分、组合数学、图论、优化、概率与统计训练。',
    econLabel: '经济学',
    econText: '学习过微观经济学、宏观经济学与世界经济相关课程。',
    scienceLabel: '其他理科背景',
    scienceText: '还修读过大学层面的化学与物理课程。',
    toolsLabel: '工具与系统',
    toolsText: '使用 VS Code、Cursor、Vim、Git、LaTeX、Microsoft Office，并使用 Final Cut Pro 与剪映进行剪辑；熟悉 Linux、macOS 与 Windows。',
    englishLevel: '英语 · 熟练',
    chineseLevel: '中文 · 母语',

    interestsKicker: '学习之外',
    interestsTitle: '体育与搏击',
    interestsIntro: '乒乓球、泰拳、散打与咏春持续影响着我的训练、比赛与思考方式。',
    personalb1: '通过滑铁卢大学乒乓球校队选拔并加入 B 队。',
    personalb2: '曾在国内习练咏春拳与散打。',
    personalb3: '在滑铁卢大学继续进行泰拳训练。',
    galleryChina: '国内训练',
    galleryWaterloo: '滑铁卢训练',
    galleryTeam: '校队选拔',

    footerLocation: '来自福州 · 现居滑铁卢',
    footerRights: '个人学术主页。'
  }
};

const root = document.documentElement;
const header = document.getElementById('siteHeader');
const languageToggle = document.getElementById('languageToggle');
const themeToggle = document.getElementById('themeToggle');
const progress = document.getElementById('scrollProgress');
const backToTop = document.getElementById('backToTop');
const currentYear = document.getElementById('currentYear');

const safeStorage = {
  get(key) {
    try {
      return localStorage.getItem(key);
    } catch {
      return null;
    }
  },

  set(key, value) {
    try {
      localStorage.setItem(key, value);
    } catch {
      // 浏览器禁止本地存储时，网页仍然可以正常使用
    }
  }
};

function applyLanguage(language) {
  const dictionary = translations[language] || translations.en;

  document.querySelectorAll('[data-i18n]').forEach((element) => {
    const key = element.dataset.i18n;

    if (dictionary[key]) {
      element.textContent = dictionary[key];
    }
  });

  root.lang = language === 'zh' ? 'zh-CN' : 'en';

  languageToggle.textContent = language === 'zh' ? 'EN' : '中文';
  languageToggle.dataset.language = language;

  languageToggle.setAttribute(
    'aria-label',
    language === 'zh' ? 'Switch to English' : '切换到中文'
  );

  document.title =
    language === 'zh'
      ? '林灿然（Canran Bruce Lin）｜福州 · 滑铁卢大学'
      : 'Canran (Bruce) Lin | Fuzhou · University of Waterloo';

  safeStorage.set('preferred-language', language);
}

const initialLanguage =
  safeStorage.get('preferred-language') === 'zh' ? 'zh' : 'en';

applyLanguage(initialLanguage);

languageToggle.addEventListener('click', () => {
  const nextLanguage =
    languageToggle.dataset.language === 'zh' ? 'en' : 'zh';

  applyLanguage(nextLanguage);
});

function applyTheme(theme) {
  root.dataset.theme = theme;
  themeToggle.textContent = theme === 'dark' ? '☀' : '◐';

  themeToggle.setAttribute(
    'aria-label',
    theme === 'dark'
      ? 'Switch to light theme'
      : 'Switch to dark theme'
  );

  safeStorage.set('preferred-theme', theme);
}

const savedTheme = safeStorage.get('preferred-theme');

const systemDark =
  window.matchMedia &&
  window.matchMedia('(prefers-color-scheme: dark)').matches;

applyTheme(
  savedTheme === 'dark' || savedTheme === 'light'
    ? savedTheme
    : systemDark
      ? 'dark'
      : 'light'
);

themeToggle.addEventListener('click', () => {
  applyTheme(root.dataset.theme === 'dark' ? 'light' : 'dark');
});

function updateScrollUI() {
  const top = window.scrollY || document.documentElement.scrollTop;

  const total =
    document.documentElement.scrollHeight - window.innerHeight;

  const percentage =
    total > 0 ? Math.min(100, (top / total) * 100) : 0;

  progress.style.width = `${percentage}%`;

  header.classList.toggle('scrolled', top > 10);
  backToTop.classList.toggle('visible', top > 650);
}

window.addEventListener('scroll', updateScrollUI, {
  passive: true
});

window.addEventListener('resize', updateScrollUI);

updateScrollUI();

backToTop.addEventListener('click', () => {
  window.scrollTo({
    top: 0,
    behavior: 'smooth'
  });
});

if (currentYear) {
  currentYear.textContent = new Date().getFullYear();
}

const revealElements = document.querySelectorAll('.reveal');

if ('IntersectionObserver' in window) {
  const revealObserver = new IntersectionObserver(
    (entries, observer) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) {
          return;
        }

        entry.target.classList.add('in-view');
        observer.unobserve(entry.target);
      });
    },
    {
      threshold: 0.12,
      rootMargin: '0px 0px -35px'
    }
  );

  revealElements.forEach((element) => {
    revealObserver.observe(element);
  });
} else {
  revealElements.forEach((element) => {
    element.classList.add('in-view');
  });
}

const sections = [
  ...document.querySelectorAll('main section[id]')
];

const navAnchors = [
  ...document.querySelectorAll('.nav-links a')
];

if ('IntersectionObserver' in window) {
  const sectionObserver = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) {
          return;
        }

        navAnchors.forEach((anchor) => {
          const isCurrent =
            anchor.getAttribute('href') === `#${entry.target.id}`;

          anchor.classList.toggle('active', isCurrent);
        });
      });
    },
    {
      rootMargin: '-28% 0px -60%',
      threshold: 0
    }
  );

  sections.forEach((section) => {
    sectionObserver.observe(section);
  });
}

const lightbox = document.getElementById('lightbox');
const lightboxImage = document.getElementById('lightboxImage');
const lightboxCaption = document.getElementById('lightboxCaption');
const lightboxClose = document.getElementById('lightboxClose');

function openLightbox(source, caption) {
  lightboxImage.src = source;
  lightboxImage.alt = caption;
  lightboxCaption.textContent = caption;

  lightbox.hidden = false;

  document.body.classList.add('lightbox-open');
  lightboxClose.focus();
}

function closeLightbox() {
  lightbox.hidden = true;
  lightboxImage.removeAttribute('src');

  document.body.classList.remove('lightbox-open');
}

document.querySelectorAll('[data-lightbox]').forEach((card) => {
  card.addEventListener('click', () => {
    openLightbox(
      card.dataset.lightbox,
      card.dataset.caption
    );
  });
});

lightboxClose.addEventListener('click', closeLightbox);

lightbox.addEventListener('click', (event) => {
  if (event.target === lightbox) {
    closeLightbox();
  }
});

document.addEventListener('keydown', (event) => {
  if (event.key === 'Escape' && !lightbox.hidden) {
    closeLightbox();
  }
});
